- name: 'Tags'
  id: tags
  run: |
    echo "Input Tags: ${{ inputs.tags }}"
    echo "GITHUB_REF_NAME: ${GITHUB_REF_NAME}"
    echo "github.event_name: ${{ github.event_name }}"
    if [ "${{ github.event_name }}" = "workflow_dispatch" ];then
      if [ -n "${{ inputs.tags }}" ];then
        echo "Parsing Input Tags..."
        TAGS=""
        IFS=',' read -ra INPUT <<< "${{ inputs.tags }}"
        for tag in "${INPUT[@]}";do
          echo "${REGISTRY}/${USER}/${REPO}:${tag}"
          TAGS+="${REGISTRY}/${USER}/${REPO}:${tag},"
        done
        TAGS="$(echo ${TAGS} | sed 's/,*$//g')"
      else
        echo "Using Default Tags..."
        TAGS="${REGISTRY}/${USER}/${REPO}:${GITHUB_REF_NAME}"
        TAGS+=",${REGISTRY}/${USER}/${REPO}:latest"
      fi
      echo "tags=${TAGS}" >> $GITHUB_OUTPUT
      echo "Parsed Tags: ${TAGS}"
    else
      TAGS="${REGISTRY}/${USER}/${REPO}:${GITHUB_REF_NAME}"
      if [ "${{ github.event.release.prerelease }}" != "true" ];then
        TAGS+=",${REGISTRY}/${USER}/${REPO}:latest"
      fi
      echo "tags=${TAGS}" >> $GITHUB_OUTPUT
      echo "Parsed Tags: ${TAGS}"
    fi
    echo "APP_VERSION=${GITHUB_REF_NAME}" >> app/.env
    echo "APP_VERSION: ${GITHUB_REF_NAME}"
