---
load: "1"
kind: pipeline
name: test

trigger:
  event:
    - push

steps:
- name: test
  image: docker:dind
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
  commands:
  - docker info

volumes:
- name: dockersock
  host:
    path: /var/run/docker.sock
