---
load: "1"
kind: pipeline
name: test

platform:
  os: linux
  arch: arm64

trigger:
  event:
    - push

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock

steps:
- name: info
  image: docker:dind
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
  commands:
  - docker info
