IMAGE: python:3.6

SCRIPT:
    - pip install --upgrade pip
    - pip install -r requirements.txt
    - pip install coverage
    - pip install flake8
    - cp settings.ini.example settings.ini
    - python manage.py makemigrations
    - python manage.py migrate
    - coverage run manage.py test
    - coverage xml
    - flake8
    - this is not a command
