name: "⚠️ Report an Issue"
description: "Something Not Working Right? Please let us know..."
title: "[Bug] "
labels: ["bug"]
assignees:
  - smashedr

body:
  - type: markdown
    attributes:
      value: |
        All bugs that we can verify will be fixed. Thank you for taking the time to make this report!

  - type: input
    id: website
    validations:
      required: false
    attributes:
      label: Site Link
      description: Please provide a link to the site you are having issues on if possible.
      placeholder: https://example.com/

  - type: textarea
    id: description
    validations:
      required: true
    attributes:
      label: Details
      description: Please Describe the Issue you are Experiencing.
      placeholder: Provide as many details as you can...

  - type: textarea
    id: logs
    validations:
      required: true
    attributes:
      label: Paste Support Information
      description: Open the Extension Options, Scroll to the Bottom, Click Copy Support Information and Paste Below.
      render: shell
#
#  - type: dropdown
#    id: version
#    validations:
#      required: true
#    attributes:
#      label: Version
#      description: What version of our software are you running?
#      options:
#        - 1.0.2 (Default)
#        - 1.0.3 (Edge)
#      default: 0
#
#  - type: dropdown
#    id: browsers
#    attributes:
#      label: What browsers are you seeing the problem on?
#      multiple: true
#      options:
#        - Firefox
#        - Chrome
#        - Safari
#        - Microsoft Edge
#
#  - type: checkboxes
#    id: terms
#    attributes:
#      label: Code of Conduct
#      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com).
#      options:
#        - label: I agree to follow this project's Code of Conduct
#          required: true
