blank_issues_enabled: true
contact_links:
  - name: Join the Discord Server
    about: Chat with us about Issues, Features, Questions and More...
    url: https://discord.gg/wXy6m2X8wY
  - name: View More Apps
    about: Contact us for all your consulting $ needs!
    url: https://cssnr.github.io/
