name: "Test Docker Stack Deploy"

on:
  push:

jobs:
  deploy:
    name: "Deploy"
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      - name: "Docker Stack Deploy"
        uses: hosted-domains/stack-deploy-action@master
        with:
          host: ${{ secrets.DOCKER_HOST }}
          user: ${{ secrets.DOCKER_USER }}
          pass: ${{ secrets.DOCKER_PASS }}
          port: ${{ secrets.DOCKER_PORT }}
          name: "django-files-test"
          file: "docker-compose-swarm.yaml"
