name: Test

on:
  push:

env:
  ZIPLINE_URL: http://zipline:3000/

jobs:
  deploy:
    name: Full Test
    timeout-minutes: 5
    if: ${{ !contains(github.event.head_commit.message, '#noci') }}
    strategy:
      matrix:
        os: [ubuntu-22.04]
        version: ["3.11"]
    runs-on: ${{ matrix.os }}

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DATABASE: postgres

      zipline:
        image: ghcr.io/diced/zipline:latest
        env:
          DEBUG: true
          CORE_PORT: 3000
          CORE_RETURN_HTTPS: false
          CORE_SECRET: H8Y9lSs48w3HwOgFfpaF0G
          CORE_DATABASE_URL: postgres://postgres:postgres@postgres/postgres

    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      - name: "Setup Python ${{ matrix.version }}"
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.version }}

      - name: "Setup pip ${{ matrix.version }}"
        run: |
          python -m pip install -U pip
          python -m pip install -Ur requirements.txt
          pip install flake8 coverage

      - name: "Lint ${{ matrix.version }}"
        run: flake8 zipline.py

      - name: "Test ${{ matrix.version }}"
        run: |
          python -m pip install -e .
          echo ZIPLINE_URL: ${ZIPLINE_URL}
          curl -Iv ${ZIPLINE_URL}
          #while ! curl --silent ${ZIPLINE_URL}; do sleep 1; done
          export ZIPLINE_TOKEN=$(python3 get_test_token.py)
          echo ZIPLINE_TOKEN: ${ZIPLINE_TOKEN}
          zipline zipline.py
