name: "Test"

on:
  push:

jobs:
  test:
    name: "Test"
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

#      - name: "Upload Artifact"
#        uses: actions/upload-artifact@v3
#        with:
#          name: "artifacts"
#          path: "examples/"

      - name: "Push Artifacts"
        uses: hosted-domains/gh-push-artifacts@master
        with:
          path: "examples"
          host: ${{ secrets.RSYNC_HOST }}
          user: ${{ secrets.RSYNC_USER }}
          pass: ${{ secrets.RSYNC_PASS }}
          port: "2222"
          base: "/static"
          webhost: "http://jammy.local:8000"
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
