name: "Test"

on:
  push:

jobs:
  test:
    name: "Test"
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: "Upload Artifact"
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: examples/

      - name: "Push Artifacts"
        uses: hosted-domains/gh-push-artifacts@master
        with:
          name: artifacts
