name: "Test"

on:
  push:

jobs:
  test:
    name: "Test"
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

#      - name: "Upload Artifact"
#        uses: actions/upload-artifact@v3
#        with:
#          name: "artifacts"
#          path: "examples/"

      - name: "Push Artifacts"
        uses: hosted-domains/gh-push-artifacts@master
        with:
          path: "examples"
          host: "intranet.cssnr.com"
          user: ${{ secrets.SFTP_USER }}
          pass: ${{ secrets.SFTP_PASS }}
          port: "2222"
          base: "static"
