name: "Test Tag"

on:
  push:
    tags:
      - '*.*.*'
  workflow_dispatch:
    inputs:
      tags:
        description: 'Tags: comma,separated'
        required: true
        default: 'latest'

jobs:
  tags:
    name: "Tags"
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      - name: "Not Pre-Release"
        if: ${{ !github.event.prerelease }}
        run: |
          echo "NOT - PRERELEASE"

      - name: "Pre-Release"
        if: ${{ github.event.prerelease }}
        run: |
          echo "YES - PRERELEASE"

      - name: "Update Manifest"
        run: |
          echo "github.event.prerelease: ${{ github.event.prerelease }}"
          echo "github.event.release.prerelease: ${{ github.event.release.prerelease }}"
          echo "github.event: ${{ github.event }}"
          echo "github.event_name: ${{ github.event_name }}"
          if [ "${{ github.event_name }}" = "workflow_dispatch" ];then
            echo "WORKFLOW DISPATCH EVENT HERE"
          fi
          echo "inputs.tags: ${{ inputs.tags }}"
          echo "GITHUB_REF_NAME: ${GITHUB_REF_NAME}"
#          echo "${GITHUB_REF_NAME}" > version.txt
#          git status
#          git diff

      - name: "Tags"
        id: tags
        run: |
          echo "Input Tags: ${{ inputs.tags }}"
          echo "Version (ref): ${GITHUB_REF_NAME}"
          if [ "${{ github.event_name }}" = "workflow_dispatch" ];then
            TAGS=""
            IFS=',' read -ra INPUT <<< "${{ inputs.tags }}"
            for tag in "${INPUT[@]}";do
              echo "${REGISTRY}/${USER}/${REPO}:${tag}"
              TAGS+="${REGISTRY}/${USER}/${REPO}:${tag},"
            done
            TAGS="$(echo ${TAGS} | sed 's/,*$//g')"
            echo "tags=${TAGS}" >> $GITHUB_OUTPUT
            echo "Parsed Tags: ${TAGS}"
          else
            TAGS="${REGISTRY}/${USER}/${REPO}:latest,${REGISTRY}/${USER}/${REPO}:${GITHUB_REF_NAME}"
            echo "tags=${TAGS}" >> $GITHUB_OUTPUT
            echo "Parsed Tags: ${TAGS}"
          fi
          echo "APP_VERSION=${GITHUB_REF_NAME}" >> .env
          echo "APP_VERSION: ${APP_VERSION}"

#      - name: "Commit files"
#        run: |
#          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
#          git config --local user.name "github-actions[bot]"
#          git commit -a -m "Version ${GITHUB_REF_NAME}"
#
#      - name: "Push changes"
#        uses: ad-m/github-push-action@master
#        with:
#          github_token: ${{ secrets.GITHUB_TOKEN }}
#          branch: master
