name: Build

on:
  release:
    types: [published]

env:
  REGISTRY: ghcr.io
  USER: ${{ github.repository_owner }}
  REPO: ${{ github.repository }}

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: ./nginx/Dockerfile
            image: ${{ env.REGISTRY }}/${{ env.USER }}/${{ env.REPO }}-nginx
          - dockerfile: ./app/Dockerfile
            image: ${{ env.REGISTRY }}/${{ env.USER }}/${{ env.REPO }}-app
    permissions:
      contents: read
      packages: write

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4

      #      - name: 'Docker Login'
      #        uses: docker/login-action@v2
      #        with:
      #          registry: ${{ env.REGISTRY }}
      #          username: ${{ secrets.GHCR_USER }}
      #          password: ${{ secrets.GHCR_PASS }}

      #      - name: 'Setup Buildx'
      #        uses: docker/setup-buildx-action@v2
      #        with:
      #          platforms: linux/amd64,linux/arm64

      - name: 'Docker Metadata'
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ matrix.image }}

      - name: 'Debug'
        run: |
          echo "file: ${{ matrix.dockerfile }}"
          echo "tags: ${{ matrix.dockerfile }}"
          echo "labels: ${{ matrix.dockerfile }}"

#      - name: 'Build and Push'
#        uses: docker/build-push-action@v4
#        with:
#          context: .
#          platforms: linux/amd64,linux/arm64
#          push: true
#          file: ${{ matrix.dockerfile }}
#          tags: ${{ steps.meta.outputs.tags }}
#          labels: ${{ steps.meta.outputs.labels }}
