name: Build

on:
  release:
    types: [published]

env:
  REGISTRY: ghcr.io
  USER: ${{ github.repository_owner }}

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: ./nginx/Dockerfile
            image: ghcr.io/${{ github.repository }}-nginx
          - dockerfile: ./app/Dockerfile
            image: ghcr.io/${{ github.repository }}-app
    permissions:
      contents: read
      packages: write

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4

      #      - name: 'Docker Login'
      #        uses: docker/login-action@v2
      #        with:
      #          registry: ${{ env.REGISTRY }}
      #          username: ${{ secrets.GHCR_USER }}
      #          password: ${{ secrets.GHCR_PASS }}

      #      - name: 'Setup Buildx'
      #        uses: docker/setup-buildx-action@v2
      #        with:
      #          platforms: linux/amd64,linux/arm64

      - name: 'Docker Metadata'
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ matrix.image }}
          flavor: |
            latest=false
          tags: |
            type=ref,event=tag,value=${{ github.ref }}
            type=raw,value=latest,enable=${{ ! github.event.release.prerelease  }}

      - name: 'Debug 1'
        run: |
          echo "file: ${{ matrix.dockerfile }}"
          echo "image: ${{ matrix.image }}"

      #      - name: 'JS'
      #        #uses: smashedr/javascript-action@master
      #        uses: ./.github/update-json-value
      #        with:
      #          file: src/manifest.json

      - name: 'Docker Tags'
        #        uses: ./.github/docker-tags
        uses: smashedr/js-test-action@master
        id: tags
        with:
          images: ${{ matrix.image }}

      - name: 'Debug 2'
        run: |
          echo "file: ${{ matrix.dockerfile }}"
          echo "image: ${{ matrix.image }}"
          echo "tags: ${{ steps.tags.outputs.tags }}"
          echo "meta: ${{ steps.meta.outputs.tags }}"

#      - name: 'Build and Push'
#        uses: docker/build-push-action@v4
#        with:
#          context: .
#          platforms: linux/amd64,linux/arm64
#          push: true
#          file: ${{ matrix.dockerfile }}
#          tags: ${{ steps.meta.outputs.tags }}
#          labels: ${{ steps.meta.outputs.labels }}
