name: Build

on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'Tags to Push'
        required: true
        default: 'latest'

env:
  REGISTRY: "ghcr.io"
  USER: "django-files"
  REPO: "django-files"

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: "Testing 1"
        id: step1
        run: |
          echo ${{ inputs.tags }}
          NEW_TAGS=""
          IFS=',' read -ra TAGS <<< "${{ inputs.tags }}"
          for tag in "${TAGS[@]}"; do
            echo "${REGISTRY}/${USER}/${REPO}:${tag}"
            NEW_TAGS+="${REGISTRY}/${USER}/${REPO}:${tag},"
          done
          echo "tags=${{ inputs.tags }}" >> $GITHUB_OUTPUT

      - name: "Testing 2"
        id: step2
        run: |
          echo ${{ steps.step1.outputs.tags }}
#      - name: "Checkout"
#        uses: actions/checkout@v3
#
#      - name: "Setup Buildx"
#        uses: docker/setup-buildx-action@v2
#        with:
#          platforms: linux/amd64,linux/arm64
#
#      - name: "Docker Login"
#        uses: docker/login-action@v2
#        with:
#          registry: ghcr.io
#          username: ${{ secrets.GHCR_USER }}
#          password: ${{ secrets.GHCR_PASS }}
#
#      - name: "Build and Push"
#        uses: docker/build-push-action@v4
#        with:
#          context: .
#          platforms: linux/amd64,linux/arm64
#          push: true
#          tags: ghcr.io/django-files/django-files:latest
