name: "Test Cloudflare Cache Purge"

on:
  workflow_dispatch:

jobs:
  test:
    name: "Test"
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: "Purge Cache"
        uses: cssnr/cf-purge-cache-action@master
        with:
          zone: cssnr.com
          token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
