name: "Test Tags"

on:
  workflow_dispatch:
  release:
    types: [published]
  push:
    tags:
      - "*"

jobs:
  test:
    name: "Test"
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      #      - name: "Checkout"
      #        uses: actions/checkout@v4

      - name: "Update Tags"
        uses: smashedr/update-tags-action@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          major: true
          minor: true
