name: Redis Test

on:
  push:
  workflow_dispatch:
    inputs:
      number:
        description: 'Test Number'
        required: false
        default: '420'

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis
        ports:
          - 6379:6379

    steps:
      - name: Connect to Redis
        run: |
          echo number: ${INPUT_NUMBER}
          apt-get install redis
          redis-cli -h localhost ping
