name: "Test"

on:
  push:
    branches:
      - master
  release:
    types: [published]

jobs:
  test:
    name: "Test"
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      #      - name: "Test"
      #        id: test
      #        #uses: smashedr/javascript-action@master
      #        #uses: ./.github/update-json-value
      #        #uses: ./.github/js-test-action
      #        #uses: ./.github/parse-issue-form-action
      #        with:
      #          token: ${{ secrets.PORTAINER_TOKEN }}

      #      - name: "Portainer"
      #        id: test
      #        uses: ./.github/portainer-swarm-deploy
      #        with:
      #          url: https://jammy.local:9443
      #          token: ${{ secrets.PORTAINER_TOKEN }}
      #          name: node-discord-hook
      #          file: docker-compose.yaml
      #          repo: https://github.com/smashedr/node-discord-hook

      #      - name: "Tags"
      #        id: test
      #        uses: ./.github/update-version-tags-action
      #        with:
      #          token: ${{ secrets.GITHUB_TOKEN }}
      #          tags: "fake"

      - name: "Push Artifacts"
        uses: ./.github/push-artifacts-action
        with:
          path: "tests/screenshots/"
          host: ${{ secrets.RSYNC_HOST }}
          user: ${{ secrets.RSYNC_USER }}
          pass: ${{ secrets.RSYNC_PASS }}
          port: ${{ secrets.RSYNC_PORT }}
          base: "/home/test/static"
          webhost: "https://artifacts.hosted-domains.com"
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
