name: "Test VT"

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  test:
    name: "Test"
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      - name: "VirusTotal"
        uses: cssnr/virustotal-action@limiter
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          vt_api_key: ${{ secrets.VT_API_KEY }}
          update_release: true
          rate_limit: 1
