name: Redis Test

on:
  push:
  workflow_call:
    inputs:
      number:
        description: 'Number'
        type: string
        required: true
        default: '420'

env:
  TEST_NUMBER: ${{ github.event.inputs.number || '420' }}

jobs:
  test:
    runs-on: ubuntu-latest

#    services:
#      redis:
#        image: redis
#        ports:
#          - 6379:6379

    steps:
      - name: Connect to Redis
        run: |
          echo github.event.inputs.number: ${{ github.event.inputs.number }}
          echo inputs.number: ${{ inputs.number }}
          echo number: ${TEST_NUMBER}
#          sudo apt-get install redis
#          redis-cli -h localhost ping
